<?php

namespace App\Http\Controllers;

use Illuminate\View\View;

class DiscordBotGuideController extends Controller
{
    public function __invoke(): View
    {
        $appName = config('app.name');

        return view('user.discord-bot-guide', [
            'appName' => $appName,
            'automations' => $this->automations($appName),
            'commandGroups' => $this->commandGroups($appName),
            'staffCommands' => $this->staffCommands($appName),
        ]);
    }

    /**
     * @return array<int, array{
     *     id: string,
     *     title: string,
     *     icon: string,
     *     summary: string,
     *     commands: array<int, array{command: string, description: string, usage?: array<int, string>, note?: string}>
     * }>
     */
    private function commandGroups(string $appName): array
    {
        return [
            [
                'id' => 'start',
                'title' => 'Getting started',
                'icon' => 'o-link',
                'summary' => "Link your Discord identity to {$appName} and confirm that the bot can recognize you.",
                'commands' => [
                    [
                        'command' => '/verify code:<verification code>',
                        'description' => "Link your Discord account using the verification code generated by {$appName}.",
                        'usage' => [
                            "Open Settings in {$appName} and generate a Discord verification code.",
                            'Run the command in the alliance Discord server and paste the full code.',
                            'Verification codes are sensitive. Do not post or forward one to another person.',
                        ],
                    ],
                    [
                        'command' => '/ping',
                        'description' => 'Check whether the bot is online and responding to commands.',
                    ],
                ],
            ],
            [
                'id' => 'finance',
                'title' => 'Accounts and finance',
                'icon' => 'o-banknotes',
                'summary' => 'Review balances, create deposit codes, request withdrawals, and inspect financial activity.',
                'commands' => [
                    [
                        'command' => '/accounts [account]',
                        'description' => "List your {$appName} accounts or inspect the balances in one account.",
                        'note' => "Account choices autocomplete from the accounts your linked {$appName} identity is allowed to use.",
                    ],
                    [
                        'command' => '/transactions account:<account> [type] [status]',
                        'description' => 'View recent transactions for one of your accounts, optionally filtered by type or status.',
                    ],
                    [
                        'command' => '/deposit account:<account>',
                        'description' => 'Create a private deposit code for an in-game bank transfer.',
                        'usage' => [
                            "Choose the {$appName} account that should receive the deposit.",
                            'Copy the returned code into the note field of your Politics & War bank transfer.',
                            "The code expires after one hour. If an active code already exists, {$appName} safely reuses it.",
                        ],
                        'note' => "Keep the code private. {$appName} matches the code when it imports the bank transfer.",
                    ],
                    [
                        'command' => '/withdraw account:<account>',
                        'description' => 'Build and confirm a withdrawal containing money and/or resources.',
                        'usage' => [
                            'Select a source account, choose resources, and enter the requested amounts.',
                            'Review the complete request before pressing Confirm.',
                            "{$appName} rechecks ownership, account state, balance, blockade status, and withdrawal limits at confirmation.",
                        ],
                        'note' => "The same {$appName} withdrawal limits used by the website apply. Requests above those limits enter staff review instead of being sent automatically.",
                    ],
                    [
                        'command' => '/requests scope:mine [type] [status]',
                        'description' => 'See your open or completed withdrawals, grants, loans, aid, transfers, and applications in one place.',
                    ],
                ],
            ],
            [
                'id' => 'assistance',
                'title' => 'Grants, loans, and assistance',
                'icon' => 'o-lifebuoy',
                'summary' => 'Browse available programs, preview requests, and confirm submissions without leaving Discord.',
                'commands' => [
                    [
                        'command' => '/grant browse [eligible_only]',
                        'description' => "Browse available grant programs and optionally show only programs for which {$appName} reports you as eligible.",
                    ],
                    [
                        'command' => '/grant apply grant:<program> account:<account>',
                        'description' => "Preview a grant application and confirm it after {$appName} validates the program, nation, and destination account.",
                    ],
                    [
                        'command' => '/grant city account:<account>',
                        'description' => 'Preview and request the currently available city grant.',
                    ],
                    [
                        'command' => '/grant status',
                        'description' => 'View your grant and city-grant requests.',
                    ],
                    [
                        'command' => '/loan apply account:<account>',
                        'description' => 'Apply for a loan. Discord asks for the amount and a term from 1 to 52 weeks, then shows a confirmation preview.',
                    ],
                    [
                        'command' => '/loan status [loan]',
                        'description' => 'List your loans or inspect a selected loan.',
                    ],
                    [
                        'command' => '/loan pay loan:<loan> account:<account>',
                        'description' => "Preview and confirm a payment from one of your {$appName} accounts.",
                    ],
                    [
                        'command' => '/waraid apply account:<account> note:<reason>',
                        'description' => 'Choose requested resources, preview the request, and submit war aid for staff review.',
                    ],
                    [
                        'command' => '/waraid status',
                        'description' => 'View your war-aid requests and their current status.',
                    ],
                    [
                        'command' => '/rebuild apply account:<account> [note]',
                        'description' => "Ask {$appName} to calculate your rebuilding eligibility and estimate before submitting a request.",
                    ],
                    [
                        'command' => '/rebuild status',
                        'description' => 'View your rebuilding requests.',
                    ],
                ],
            ],
            [
                'id' => 'defense',
                'title' => 'Defense and intelligence',
                'icon' => 'o-shield-check',
                'summary' => "Bring {$appName} raid guidance, war context, assignments, and simulations into Discord.",
                'commands' => [
                    [
                        'command' => '/raid [nation] [sort] [limit]',
                        'description' => 'Find recommended raid targets. Members query their own nation; authorized staff may query another nation ID.',
                        'note' => 'Sort options include value, cities, and activity. Results can be limited to 5 or 10 targets.',
                    ],
                    [
                        'command' => '/war active',
                        'description' => 'View your active wars.',
                    ],
                    [
                        'command' => '/war assignments',
                        'description' => 'View war-plan and counter assignments, then acknowledge an assignment or report that you are unavailable.',
                    ],
                    [
                        'command' => '/war counter nation:<nation ID>',
                        'description' => "Get {$appName} counter guidance for a nation.",
                    ],
                    [
                        'command' => '/war simulate war:<war>',
                        'description' => 'View a concise simulation summary for a selected active war.',
                    ],
                    [
                        'command' => '/spy assignments',
                        'description' => 'View your current spy-operation assignments.',
                    ],
                ],
            ],
            [
                'id' => 'applications',
                'title' => 'Applications',
                'icon' => 'o-identification',
                'summary' => 'Start an alliance application or review the status of an application already connected to your Discord identity.',
                'commands' => [
                    [
                        'command' => '/apply nationid:<nation ID>',
                        'description' => 'Submit an alliance application and allow the bot to create the configured interview workflow.',
                    ],
                    [
                        'command' => '/applications status',
                        'description' => 'View applications associated with your linked Discord identity.',
                    ],
                ],
            ],
        ];
    }

    /** @return array<int, array{title: string, description: string, action: string}> */
    private function automations(string $appName): array
    {
        return [
            [
                'title' => 'Application interview channels',
                'description' => "The bot creates the configured interview workflow after an accepted /apply submission and forwards text messages to {$appName} for the application record.",
                'action' => 'Use the generated interview channel. Attachments and embed-only messages are not added to the transcript.',
            ],
            [
                'title' => 'War rooms and alerts',
                'description' => "The bot can create or archive war-room threads from {$appName} and deliver configured war and beige alerts.",
                'action' => 'No command is required. Follow the instructions in the generated thread or alert.',
            ],
            [
                'title' => 'Membership operations',
                'description' => "Configured departure and inactivity alerts can notify staff, while membership changes may trigger Discord role cleanup requested by {$appName}.",
                'action' => 'No member action is required. Contact staff if your Discord roles do not match your current membership.',
            ],
            [
                'title' => 'Intel report capture',
                'description' => "The configured intel channel can recognize a Politics & War intelligence-result message and submit the report to {$appName}.",
                'action' => 'Post the complete result text exactly as Politics & War provides it in the configured intel channel.',
            ],
        ];
    }

    /** @return array<int, array{command: string, description: string, note?: string}> */
    private function staffCommands(string $appName): array
    {
        return [
            [
                'command' => '/requests scope:staff-queue [type] [status]',
                'description' => 'Review the consolidated staff queue for withdrawals, grants, loans, aid, transfers, and applications.',
            ],
            [
                'command' => '/applications queue [filter]',
                'description' => 'List pending or stale applications.',
            ],
            [
                'command' => '/applications review [applicant]',
                'description' => 'Open an application review by applicant or by the current application channel, then use the Approve or Deny controls.',
            ],
            [
                'command' => '/applications approve application:<application>',
                'description' => 'Approve an application after an explicit confirmation step.',
            ],
            [
                'command' => '/applications deny application:<application>',
                'description' => 'Record a denial reason and confirm the decision.',
            ],
            [
                'command' => '/approve user:<applicant>',
                'description' => 'Run the established applicant approval workflow for a Discord user.',
            ],
            [
                'command' => '/deny user:<applicant>',
                'description' => 'Run the established applicant denial workflow for a Discord user.',
            ],
            [
                'command' => '/archivecounter war_counter_id:<ID>',
                'description' => "Archive a {$appName} war counter and lock its associated Discord thread.",
            ],
            [
                'command' => '/sweepbank [note]',
                'description' => 'Sweep the main bank into the primary offshore with an optional audit note.',
                'note' => "{$appName} permissions, idempotency, and reconciliation safeguards are applied before any transfer is accepted.",
            ],
        ];
    }
}
